### ISSUE TITLE
Move Permissions outside application scope

### ISSUE THREAD

**Issue by MotassemJa** [io-digital/ethereumj-android#1]
Please move the android:name = android.permission.INTERNET and android:name = android.permission.ACCESS_NETWORK_STATE outside the application tag scope in the Manifest file. Otherwise it will throw an error until you disable Aapt2. Which will be deprecated very soon.

**Comment by skibz** [comment]
hi @MotassemJa 
thanks for the issue post!
i'm happy to accept a pull request for this change!
otherwise i will get to this before the business week is out 👌

**Comment by MotassemJa** [comment]
@skibz Thank you for your reply. I created a pull request.

**Comment by skibz** [comment]
closes #2
